export enum Titulos {
    INPUT_CONTA_INTERNA = ("Selecione a Conta Interna"),
    INPUT_CATEGORIA = ("Selecione uma Categoria"),
    INPUT_TITULO_CONTABIL = ("Selecione Título Contábil"),
    INPUT_ORIGEM = ("Selecione a Origem"),
    INPUT_TIPO_CONTA = ("Selecione um tipo de conta"),
    INPUT_BANCO_ORIGEM = ("Informe o Banco de Origem"),
    INPUT_BANCO_DESTINO = ("Informe o Banco de Destino"),
    INPUT_AGENCIA_ORIGEM = ("Informe a agência de Origem"),
    INPUT_AGENCIA_DESTINO = ("Informe a agência de Destino"),
    INPUT_CONTA_ORIGEM = ("Informe a conta de Origem"),
    INPUT_CONTA_DESTINO = ("Informe a conta de Destino"),
    INPUT_BANCO = ("Selecione o Banco de Destino"),
    INPUT_DESCRICAO_RECEITA = ("Descreva sobre a Receita"),
    INPUT_DADOS_BANCARIOS = ("Selecione o tipo/agencia/número de destino"),
    INPUT_DATA_RECEITA = ("Informe a data"),
    INPUT_VALOR_RECEITA = ("Digite o valor da receita"),
    INPUT_VALOR_DESPESA = ("Digite o valor da despesa"),
    INPUT_PAGADOR = ("Informe quem te pagou"),
    INPUT_NOME_BALANCO = ("Informe o nome do balanço."),
    INPUT_TIPO_BALANCO = ("Escolha um tipo do balanço."),
    INPUT_TIPO_CATEGORIA_TITULO_BALANCO = ("Escolha por categoria ou titúlo contábil."),
    INPUT_CATEGORIA_BALANCO = ("Informe a categoria do balanço."),
    INPUT_TIPO_VISUALIZACAO_BALANCO = ("Escolha um tipo de gráfico."),
    INPUT_BENEFICIARIO = ("Informe o beneficiário")
}